class_name E2EProtocol


const PROTOCOL_VERSION := 1
const MAX_FRAME_BYTES := 16 * 1024 * 1024
const DEFAULT_COMMAND_TIMEOUT_SECONDS := 5.0
const WAIT_MARGIN_SECONDS := 1.0
const ORPHAN_GRACE_SECONDS := 2.0
